name = "technical_modpack"
author = "Karotte128"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "331fd7728574c256155291078d5434020a9a0dfcedb6323b8e76eb413114feec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
